### PR TITLE
Replace JSONcpp with RapidJSON

### PR DESCRIPTION
**Pull request by sjanzou**
run export_config, defaults, ssc tests and landbosse

### CODE REVIEW

**Comment by sjanzou** [comment]
Goes with SAM pull request 782 https://github.com/NREL/SAM/pull/782

**Review by brtietz — CHANGES_REQUESTED** [review]
When I try to run landbosse, it just spins forever. Pulling things up in the debugger it looks like too many escape characters have been added to the file path in the input JSON:

 | input_dict_as_text | "{'weather_file_path':'C:\\\\Users\\\\bmirletz\\\\source\\\\repos\\\\sam_dev\\\\sam\\\\deploy\\\\wind_resource\\\\WY Southern-Flat Lands.srw','interconnect_voltage_kV':137.0,'distance_to_interconnect_mi':0.0,'depth':1.0... | const std::string &

Unrelated to the changes in this PR, is there a way to introduce more error checking into the for loop on line 285 of call_python_module_windows? It seems like either:
(1) There should be some maximum number of cycles that this should run before exiting to an error. AND/OR
(2) It should be checking std::err in addition to std::out to pick up on errors like this.
I'm fine to solve that in a patch, but this infinite loop makes for some fun debugging...

**Comment by brtietz** [comment]
It looks like the clipboard removed some of the backslashes. Here's a screenshot of the debugger that shows (what I suspect is) the issue:

image

**Review by cpaulgilman — COMMENTED** [review]
In my test of LandBosse from the UI, SAM crashes when I check **Enable Land-Based Balance of System Cost Model** on the Installation Costs page for a Wind / Single Owner case.

**Comment by brtietz** [comment]
Update after some additional testing: if I install landbosse from develop and check the box, it works just fine. If I remove deploy/runtime/python-3.7.6 and attempt to re-install, SAM crashes. At least the behavior is consistent with Paul!

**Comment by sjanzou** [comment]
Testing now...

**Comment by sjanzou** [comment]
That is the exact behavior in 2020.11.29.r2... Isn't that what is expected
of anything Python related? ;-)

**Comment by sjanzou** [comment]
Paul,

Are you building from develop or this pull request?

Both will crash along with 2020.11.29.r2 if you delete the
deploy/runtime/python-3.7.6 folder and then attempt to rerun landbosse...

**Comment by sjanzou** [comment]
I guess that will be a separate issue that I will fix in a separate pull
request.

**Comment by sjanzou** [comment]
> It looks like the clipboard removed some of the backslashes. Here's a screenshot of the debugger that shows (what I suspect is) the issue:
> 
> image

None of that code was touched for this pull request... Is landbosse working any differently from the 2020.11.29.r2 release?

**Comment by cpaulgilman** [comment]
> Paul, Are you building from develop or this pull request? Both will crash along with 2020.11.29.r2 if you delete the deploy/runtime/python-3.7.6 folder and then attempt to rerun landbosse...

I built from the RapidJSON branch for both SAM and SSC. The runtime folder has a python folder with install_python.ps1, install_python.sh, landbosse.json, and python_config.json, which I guess are the files SAM uses to install python. There is no python-3.7.6 folder. (If I change the name of the folder from python to python-3.7.6 and start SAM I get a message box "Unhandled unknown exception; terminating the application.")

**Comment by sjanzou** [comment]
> > Paul, Are you building from develop or this pull request? Both will crash along with 2020.11.29.r2 if you delete the deploy/runtime/python-3.7.6 folder and then attempt to rerun landbosse...
> 
> I built from the RapidJSON branch for both SAM and SSC. The runtime folder has a python folder with install_python.ps1, install_python.sh, landbosse.json, and python_config.json, which I guess are the files SAM uses to install python. There is no python-3.7.6 folder. (If I change the name of the folder from python to python-3.7.6 and start SAM I get a message box "Unhandled unknown exception; terminating the application.")

Here is my folder after doing a clean build with develop branches of lk and wex and RapidJSON branches of ssc and SAM
image

Then Wind->Single Owner -> enable landbosse
image


The issue with crashing was due to the python files that were checked into the runtime/python folder.
I added a reset folder with the intial install files so that SAM does not crash - again unreleated to this pull request.

The python.config file (if no runtime/python/python-3.7.6 folder) should look like
image


After landbosse enabled and 1200 python files and 285MB installated into the  runtime/python/python-3.7.6 folder, the the python.config file should look likeL
image

**Comment by sjanzou** [comment]
> It looks like the clipboard removed some of the backslashes. Here's a screenshot of the debugger that shows (what I suspect is) the issue:
> 
> image

working with last commit to SAM... should be ready to go

**Comment by cpaulgilman** [comment]
LandBOSSE works for me now. Sorry that had to come up as part of this PR! ;)

**Review by cpaulgilman — APPROVED** [review]

**Comment by sjanzou** [comment]
> LandBOSSE works for me now. Sorry that had to come up as part of this PR! ;)

@cpaulgilman, that was great! Gave us a headstart on testing during lockdown!

**Comment by sjanzou** [comment]
> When I try to run landbosse, it just spins forever. Pulling things up in the debugger it looks like too many escape characters have been added to the file path in the input JSON:
> 
> | input_dict_as_text | "{'weather_file_path':'C:\\Users\\bmirletz\\source\\repos\\sam_dev\\sam\\deploy\\wind_resource\\WY Southern-Flat Lands.srw','interconnect_voltage_kV':137.0,'distance_to_interconnect_mi':0.0,'depth':1.0... | const std::string &
> 
> Unrelated to the changes in this PR, is there a way to introduce more error checking into the for loop on line 285 of call_python_module_windows? It seems like either: (1) There should be some maximum number of cycles that this should run before exiting to an error. AND/OR (2) It should be checking std::err in addition to std::out to pick up on errors like this. I'm fine to solve that in a patch, but this infinite loop makes for some fun debugging...

Addressed in commit fc3d2eca8bc02ddd2a350bfdb0975f418321cd64

**Review by brtietz — APPROVED** [review]

**Comment by dguittet** [comment]
@sjanzou @cpaulgilman Great job adapting the LandBOSSE workflow's Python Installation from JSONCpp to RapidJSON! Looks like there were unexpected snags with writing and reading the JSON config files. And also re-installing Python after a manual deletion.

Apologies, I should have documented how this Python installation works, and how to adapt it! Can do that after the release. Anything else that came up while you were struggling through this obtuse, undocumented workflow that I should add to the documentation?

**Pull request merged**
