### PR TITLE
Updated Wind Offshore BOS library and compute module

### PR DESCRIPTION
**Pull request by gbarter**
Hi Janine and SAM Team,

The changes here reflect a significant code cleanup of the lib_wind_obos model.  I have created new data structures, fixed bugs, and made the code more readable.  Note that I have added some additional files (lib_wind_obos_*) to facilitate the cleanup and data structures, but it your team prefers, we can stuff everything back into one file.  I have also switched variable default values and units to be drawn from a csv-file, so that it can also be used by python and other wrapper codes.  The compute module now also draws from this same file ultimately for consistency.  At this point I am still having trouble with SAM using the new compute model, although the code builds without error.

Let me know how I can help further,
Garrett

### CODE REVIEW

**Comment by nickdiorio** [comment]
Thanks @gbarter, and sorry for the delay.  In general we have no problem with using additional libraries.  The reading of defaults from a CSV file may need to revisited, but we'll take a look.

It looks like the code fails to build in Linux, but it is probably related to the generation of warning.  We'll let you know, thanks for submitting.

**Comment by sjanzou** [comment]
@gbarter, Please take a look at https://travis-ci.org/NREL/ssc/jobs/361405467 lines 2755 through 2778. We need all pull requests to pass the Travis-CI builds on Linux before we can merge. Also, what trouble are you having using SAM with the new compute module? I have checked out your pull request and am going through the changes you described and will let you know what I find. Thanks!

**Comment by sjanzou** [comment]
@gbarter, we distribute the ssc.dll (Windows), ssc.so (Linux), and ssc.dylib (OS X) as standalone callable libraries that are used by several clients on several platforms. Also, we have a csv reader in the wex library that can be accessed through the SDKTool or SAM to read csv files.

Since the compute modules run on several platforms without external dependencies, we cannot support the csv file "shared/wind_obos_defaults.csv" as being included with the library. Furthermore, we need all compute modules included in the ssc project to be able to be callable and execute without any external file dependencies.

The lib_pv_shade_loss_mpp in the shared folder show an alternative for external lookups that is distributable according to the ssc standards. 

Sorry, we cannot merge your pull request at this time.

**Comment by janinefreeman** [comment]
@gbarter I am out of town at the moment, but I'll touch base with you when I get back to figure out how to make this work. 

@nickdiorio & @sjanzou , Garrett is an NREL employee and has a lot of fixes for the Wind OBOS compute module. He and I discussed that it is less than ideal to have an external file dependency, but it is the cleanest path forward for sharing the code with the WISDEM tool. We'll have to figure out some way to make this work, (perhaps encoding the information in the CSV as part of the OBOS compute module) but can deal with it when I return.

Thanks everyone!

**Comment by sjanzou** [comment]
@gbarter, we just had out SAM meeting and further discussed the pull request and what you are trying to do and we will figure out how to make it work. We will finalize when Janine gets back. Thanks!

**Comment by gbarter** [comment]
No problem.  If we need to reduce the file-footprint, not big deal.  If a csv-file for variable defaults doesn't work, maybe another text or xml-based setup would.  We essentially want to be able to use the same default values across multiple interfaces (SAM being just one) and also change them periodically without recompiling the code.  The build issues are minor- no problem fixing those.

**Comment by sjanzou** [comment]
@gbarter, I just met with Janine again and we discussed how to implement your changes. The defaults will need to be included in the compiled dll for distribution but we will make the update process as easy as possible. I will be going through your pull request code and defaults again and get back to you as soon as we have a path forward.

**Comment by sjanzou** [comment]
To update from csv defaults, run following script within SDKTool with path updated to wind_obos_defaults.csv


[wind_obos.lk.txt](https://github.com/NREL/ssc/files/2110879/wind_obos.lk.txt)

**Pull request merged**
