### PR TITLE
Changed EPW minutes to beginning of hour for accurate GHI calculations

### LINKED ISSUE #214: SAM tracker angle calculation difference between file types
Reported from @cdeline 

I am finding some odd behavior in SAM when I try to run the same simulation on a TMY3 and an EPW file.  In the case of the TMY3 file, it seems to run the way I expect – solar position is calculated 30 minutes prior to the timestamp, and GHI_calc matches GHI from the climate file.

However, when I run the same site’s EPW file using DNI&DHI inputs,  the solar position is calculated on the hour, and there’s some big differences between calculated GHI and weather file GHI :

Time stamp | Irradiance GHI SAM calculated \|   (W/m2) | Irradiance GHI from weather file   \| (W/m2)
-- | -- | --
1/2/2018 7:00 | 25 | 25
1/2/2018 8:00 | 225 | 161
1/2/2018 9:00 | 371 | 294
1/2/2018 10:00 | 457 | 395
1/2/2018 11:00 | 479 | 449
1/2/2018 12:00 | 414 | 423
1/2/2018 13:00 | 325 | 362
1/2/2018 14:00 | 222 | 281
1/2/2018 15:00 | 105 | 158
1/2/2018 16:00 | 26 | 26

I suspect that with an EPW file input, there needs to be a -30 minute time shift for calculated solar position inside SAM that isn’t happening.  

I checked earlier versions, and things were working on the half-hour back in 2012 for EPW files, but on the hour by 2014.1.14, so this is an old issue…  There also seems to have been a change between 2018.7.17 and 2018.11.11 because in the July release, the 1-axis tracker orientation was calculated on the half-hour, while in the November release it’s calculated on the hour for EPW files.

Release                EPW GHI calc                      EPW Tracker theta           TMY GHI calc      TMY tracker theta
2018.11.11           T-0                                                          T-0                          T- 0:30                   T-0:30
2018.7.17             T-0                                                          T-0:30                    T-0:30                    T-0:30
2014.1.14             T-0                                                          T-0:30                    T-0:30                    T-0:30
2012.5.11             T-0:30                                                    T-0:30                    T-0:30                    T-0:30

[WeatherFiles.zip](https://github.com/NREL/ssc/files/2680436/WeatherFiles.zip)

### PR DESCRIPTION
**Pull request by mjprilliman**
-EPW hourly files with 60 in the minute column were previously assumed to have minutes of 30 to be in between timesteps
-Minute 0 (top of hour) has calculated GHI values aligned with reported GHI values in file
-Changed minute adjustment in weather file reader to correct GHI calculations
-Closes #214

### CODE REVIEW

**Review by cpaulgilman — COMMENTED** [review]
I'm still getting inconsistencies between "GHI calculated" and "GHI from weather file." This is for the default Detailed PV / No Financials case with this EPW weather file for Granada, Spain.

[ESP_Granada.084190_SWEC.zip](https://github.com/NREL/ssc/files/7369154/ESP_Granada.084190_SWEC.zip)

image

**Comment by janinefreeman** [comment]
@mjprilliman If there's still work to be done to make this right, then I'd vote to leave it until we do the more comprehensive changes. But if there are fixes that are good to go, they may as well get merged even if there is more to do to make it ideal.

**Comment by mjprilliman** [comment]
> @mjprilliman If there's still work to be done to make this right, then I'd vote to leave it until we do the more comprehensive changes. But if there are fixes that are good to go, they may as well get merged even if there is more to do to make it ideal.

I think it would make more sense to leave it for the more comprehensive changes.

**Comment by mjprilliman** [comment]
@cpaulgilman Closing this for now to come up with more robust weather file handling changes in the future.

**Pull request closed without merging**
