### PR TITLE
Billing demand ratchets for energy charges

### PR DESCRIPTION
**Pull request by brtietz**
SSC side of billing demand for kWh/kW rates. Should be tested alongside SAM PR https://github.com/NREL/SAM/pull/627

A good rate to test with: https://en.openei.org/apps/IURDB/rate/view/5f73585d5457a3dc0b692d6f
Documentation: https://github.com/NREL/SAM-documentation/blob/master/Utility%20Rates/billing_demand_percentages/GPC_PLL_Tiered_Bill_Calc_Example_v4.xlsx

### CODE REVIEW

**Comment by cpaulgilman** [comment]
Looks good so far. I'm making a few tweaks and fixes to the UI form that I will commit tomorrow 5/26/2021. -- Paul.

**Review by mjprilliman — COMMENTED** [review]
LGTM

**Review by cpaulgilman — APPROVED** [review]

**Review by sjanzou — COMMENTED** [review]
Have you tested with https://openei.org/apps/IURDB/rate/view/5e67a8495457a3e509174f68#3__Energy
https://openei.org/apps/IURDB/rate/view/5e67afd55457a3e509174f6a#3__Energy
https://openei.org/apps/IURDB/rate/view/539fc07fec4f024c27d89cf5#3__Energy
https://openei.org/apps/IURDB/rate/view/539fc3d8ec4f024c27d8c0a7#3__Energy
kWh/hp tiered:
https://openei.org/apps/IURDB/rate/view/539fbce2ec4f024c27d8756d#3__Energy
Consumption and wallet watch credit:
https://openei.org/apps/IURDB/rate/view/5b2a82e45457a31c0be5d864#3__Energy
mixture in one period:
https://openei.org/apps/IURDB/rate/view/539f74d3ec4f024411ed0cb1#3__Energy
strange description:
https://openei.org/apps/IURDB/rate/view/539f7270ec4f024411ecf18d#1__Basic_Information
Billing demand in other energy attributes:
https://openei.org/apps/IURDB/rate/view/539fc022ec4f024c27d898f9#3__Energy

I could not find a kWh/kW daily block in the IURDB, but we should make one up and test that the daily units are working correctly.

**Comment by cpaulgilman** [comment]
@sjanzou This is a good point about compatibility with the URDB. The Georgia Power Co PLS-11 rate @brtietz linked to above has the billing demand for energy charges where the kW in the kWh/kW rate is adjusted based on a table of monthly percentages and a lookback period. The URDB data structure does not have a place to store that information, so to model it properly in SAM, you would download the rate, and then manually enter the billing demand for energy charges inputs.

The rates you list all have kWh/kW units for energy charges, but you can't tell from the URDB listing whether they involve monthly kW adjustments over a lookback period.

The URDB does have a lookback months table with a single percentage for demand charges, but not for kWh/kW energy charges. That table for demand charges only allows for a single percentage, not a percentage by month.

**Comment by sjanzou** [comment]
@brtietz, I think okay to merge and add messages for unsupported rates. Also, we do have kWh/kW daily and kWh daily units in the table but I did not find any IURDB rates with those units. Maybe we can set up a spreadsheet and test to validate or discuss further with SoCo.

**Pull request merged**
