### PR TITLE
Adaptive battery timesteps

### LINKED ISSUE #523: Adaptive battery timesteps
The current `battery_t` uses the timestep variable `dt_hr` as a fixed parameter that cannot change within a simulation. 

Allow the `battery_t` timestep to be changed from the interface, and make sure all the component models are updated with the new timestep.

Alternatives are to construct a new battery with the same state and parameters save `dt_hr`. This will be more computationally inefficient.

This is required for the battery model to be used inside EnergyPlus' power & heat convergence loops which use adaptive timesteps.

### PR DESCRIPTION
**Pull request by dguittet**
Add ChangeTimestep function to `battery_t`

Rename all `dt_hour` vars to `dt_hr`

Close #523

### CODE REVIEW

**Comment by brtietz** [comment]
The interface with battery_t looks good, but I was expecting a call to "ChangeTimestep" somewhere in battery stateful. I'd prefer to collect all of the changes to dt_hr in that function for futureproofing. I'm also missing where `params->capacity->dt_hr` is adjusted in `create_battery_params`

**Comment by dguittet** [comment]
Good point that I should add this to battery stateful so it's useable externally.

**Comment by dguittet** [comment]
Good catch on the missing `dt_hr` initialization

**Comment by dguittet** [comment]
@brtietz ready for re-review

**Review by brtietz — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
