### PR TITLE
Fix all test memory leaks and related issues in ssc and tcs

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Comment by sjanzou** [comment]
No memory leaks on macOs 12.0.1 and all tests passing on Github Actions and Windows.
We  can discuss running new tests added in Windows debug mode to prevent future leaks.
The Windows (and mac) SEH should no longer occur.

Questions and comments and updated practices are welcomed!

**Comment by sjanzou** [comment]
The jc-community contributor seems to occur from a different computer I was testing and updating on... interesting how they came into existence...

**Comment by sjanzou** [comment]
There are 6 failing tests only on macOS 12.0.1 with the Apple Silicon chip with maybe too tight of tolerance:

[ RUN      ] voltage_table_lib_battery_voltage_test.calculateMaxChargeHourly1
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:674: Failure
The difference between cap->SOC() and 99.99 is 0.010000000000005116, which exceeds 1e-2, where
cap->SOC() evaluates to 100,
99.99 evaluates to 99.989999999999995, and
1e-2 evaluates to 0.01.
[  FAILED  ] voltage_table_lib_battery_voltage_test.calculateMaxChargeHourly1 (0 ms)
[ RUN      ] voltage_table_lib_battery_voltage_test.calculateMaxChargeHourly2
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:705: Failure
The difference between max_current_calc and -0.998 is 0.0019999999999997797, which exceeds 1e-3, where
max_current_calc evaluates to -0.99999999999999978,
-0.998 evaluates to -0.998, and
1e-3 evaluates to 0.001.
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:709: Failure
The difference between cap->SOC() and 99.984 is 0.016000000000005343, which exceeds 1e-3, where
cap->SOC() evaluates to 100,
99.984 evaluates to 99.983999999999995, and
1e-3 evaluates to 0.001.
[  FAILED  ] voltage_table_lib_battery_voltage_test.calculateMaxChargeHourly2 (0 ms)
[ RUN      ] voltage_table_lib_battery_voltage_test.calculateMaxChargeHourly3
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:756: Failure
The difference between cap->SOC() and 99.99 is 0.010000000000005116, which exceeds 1e-2, where
cap->SOC() evaluates to 100,
99.99 evaluates to 99.989999999999995, and
1e-2 evaluates to 0.01.
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:757: Failure
The difference between cap->I() * model->battery_voltage() and -4615 is 1.4800619834704776, which exceeds 1, where
cap->I() * model->battery_voltage() evaluates to -4616.4800619834705,
-4615 evaluates to -4615, and
1 evaluates to 1.
[  FAILED  ] voltage_table_lib_battery_voltage_test.calculateMaxChargeHourly3 (0 ms)
[ RUN      ] voltage_table_lib_battery_voltage_test.calculateMaxChargeSubHourly1
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:786: Failure
The difference between cap->SOC() and 99.99 is 0.010000000000005116, which exceeds 1e-2, where
cap->SOC() evaluates to 100,
99.99 evaluates to 99.989999999999995, and
1e-2 evaluates to 0.01.
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:787: Failure
The difference between cap->I() * model->battery_voltage() and -5128 is 1.4222910927455814, which exceeds 1, where
cap->I() * model->battery_voltage() evaluates to -5129.4222910927456,
-5128 evaluates to -5128, and
1 evaluates to 1.
[  FAILED  ] voltage_table_lib_battery_voltage_test.calculateMaxChargeSubHourly1 (0 ms)
[ RUN      ] voltage_table_lib_battery_voltage_test.calculateMaxChargeSubHourly2
/Users/imacuser/Public/Projects/GitHub/NREL/ssc/test/shared_test/lib_battery_voltage_test.cpp:820: Failure
The difference between cap->SOC() and 99.99 is 0.010000000000005116, which exceeds 1e-2, where
cap->SOC() evaluates to 100,
99.99 evaluates to 99.989999999999995, and
1e-2 evaluates to 0.01.
[  FAILED  ] voltage_table_lib_battery_voltage_test.calculateMaxChargeSubHourly2 (0 ms)

**Comment by brtietz** [comment]
Those do look like reasonable tolerance increases in the battery.

When running this on Windows - I did get one SEH exception:

image

any ideas?

**Comment by brtietz** [comment]
Ignore my previous comment - I was running the tests on patch and failed to check out this branch.

**Comment by brtietz** [comment]
No SEH exceptions in one run on Windows (much better than usual!)

The test results make it look like increasing the tolerance is a reasonable option. It looks like most could be increased by 10%, while those currently set to a value of "1" should perhaps be "2".

**Comment by sjanzou** [comment]
> No SEH exceptions in one run on Windows (much better than usual!)
> 
> The test results make it look like increasing the tolerance is a reasonable option. It looks like most could be increased by 10%, while those currently set to a value of "1" should perhaps be "2".

Updated in commit https://github.com/NREL/ssc/pull/749/commits/63b343eaed6229710dadf383e6e463d4c27f9203 with noted tolerance update in detailed commit message.

I would like to merge sooner than later so I do not need to keep updating tests that are modified on the patch branch without these changes ;-)

**Review by brtietz — APPROVED** [review]

**Review by cpaulgilman — APPROVED** [review]
FYI -- these changes to not seem to affect simulation run times, test results generated in Windows 10, Intel Core i5-6400 2.7GHz CPU 4 Cores, 32 GB RAM, no SSD hard drive:

[sim-time-test.zip](https://github.com/NREL/ssc/files/8044594/sim-time-test.zip)

**Review by dguittet — APPROVED** [review]
Great job!

**Comment by sjanzou** [comment]
> Great job!

Thank you and thank you for the quick review!

**Comment by cpaulgilman** [comment]
> > FYI -- these changes to not seem to affect simulation run times, test results generated in Windows 10, Intel Core i5-6400 2.7GHz CPU 4 Cores, 32 GB RAM, no SSD hard drive:
> > [sim-time-test.zip](https://github.com/NREL/ssc/files/8044594/sim-time-test.zip)
> 
> @cpaulgilman, the column titles in the spreadsheet have 'release' and 'patch'... is the 'release' the patch branch of ssc and the 'patch' branch the ssc_719 branch of ssc (this branch)?
> 
> I am not sure why ETES Single Owner is now taking 63s longer....

Yes, patch = ssc_719 and release = SAM 2021.12.02.

**Pull request merged**
