### PR TITLE
restore build_sdk files

### PR DESCRIPTION
**Pull request by dguittet**
Restoring the deleted build_sdk folder to patch & develop. @sjanzou sorry for mistakenly deleting these. These all belong in the ssc repo correct?

### CODE REVIEW

**Comment by dguittet** [comment]
@sjanzou Could you take a look a this please?

**Comment by sjanzou** [comment]
@dguittet, we no longer distribute the sdk from this build process. The potential reason to restore is to have some code examples that would potentially be lost.

**Comment by sjanzou** [comment]
@cpaulgilman, @janinefreeman, please check through the 187 files that were removed and see if we would like to include any of the examples in the SAM-Documentation repo or if we want to keep the build_sdk folder in the ssc public repo or add the files to an ssc wiki.

**Comment by janinefreeman** [comment]
@sjanzou Are the system requirements for the various wrappers located somewhere in the code generator code now?

The file  build_sdk/apiwrappers/python/openei_utilityrate_billcalculator.py and associated files could be worth keeping since it shows the details of downloading a rate from the URDB and calling a utility rate compute module, although it is utilityrate3 so maybe too outdated to be useful. I'll defer to @cpaulgilman on other files in the examples folder- a lot of them are old, but I'm not sure we have any other examples of the C wrappers etc.

**Comment by sjanzou** [comment]
@janinefreeman  No, no system requirements in the generated code folders. There several user support issues involving code generation. We could keep the pdfs and copy them over to the code generation folder.

**Comment by cpaulgilman** [comment]
@sjanzou Is this an old pull request that can be safely closed without merging?

**Comment by sjanzou** [comment]
@cpaulgilman, yes, this is old and out of date and the website has many more recent examples.

**Pull request closed without merging**
