### PR TITLE
Add simulation timestep variable for stand alone battery

### PR DESCRIPTION
**Pull request by brtietz**
Add new variable timestep_minutes to control the length of the zero lifetime array within the stand alone battery. Subsequent variable checks are still enforced against this new variable.

Pairs with SAM PR https://github.com/NREL/SAM/pull/1887

Closes https://github.com/NREL/ssc/issues/994

### CODE REVIEW

**Review by mjprilliman — APPROVED** [review]

**Review by cpaulgilman — APPROVED** [review]

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
@brtietz <s>Please wait until I update Help context ID in startup to merge this.</s>

**Comment by cpaulgilman** [comment]
@brtietz Should there be an error check for BTM standalone battery when the load time step or input grid power target time step does not match the simulation time step?

**Comment by cpaulgilman** [comment]
Help revisions:

## Battery Time Step

image

## FOM Battery Dispatch

image

## BTM Battery Dispatch

image

**Review by cpaulgilman — APPROVED** [review]

**Comment by brtietz** [comment]
> @brtietz Should there be an error check for BTM standalone battery when the load time step or input grid power target time step does not match the simulation time step?

This is handled in ssc, which matches the behavior of the PV and generic system coupled configurations.

**Pull request merged**
