### PR TITLE
Patch to develop merge with fun reverts and rebases

### PR DESCRIPTION
**Pull request by brtietz**
See email thread "patch to develop merge conflicts." This is the least-bad approach I've seen from automated methods, but if we think this is bad we can throw it out and ask someone to do it manually.

Please confirm that the patch to develop changes are correct and push additional manual fixes to this branch as needed. The tests are failing at the moment, so this is definitely needed.

Please wait to merge until all 4 reviewers have reviewed, since all of you have code that might have been affected by this process.

### CODE REVIEW

**Review by mjprilliman — COMMENTED** [review]
Marine and Geothermal changes look good and shouldn't cause any issues. Need to confirm geothermal tests still pass once the project builds (build errors coming from csp cmods and solver core).

**Comment by tyneises** [comment]
Brian's merge didn't fix the merge issues with the CSP files. I replaced the poorly merged version of these files on this pull request with the Develop version. These files were not updated recently on patch with the exception of @dguittet 's commit to align cmod group names https://github.com/NREL/ssc/commit/0b50eaf8968dbccae5c7227cbd1607268bcf6dee . We need to reapply these changes in Develop.

There are also small differences between Patch and Develop in ssc/common.cpp. I don't know if the merge got this right. @sjanzou  can you please check if this file is correct in this pull request?

**Comment by sjanzou** [comment]
> Brian's merge didn't fix the merge issues with the CSP files. I replaced the poorly merged version of these files on this pull request with the Develop version. These files were not updated recently on patch with the exception of @dguittet 's commit to align cmod group names [0b50eaf](https://github.com/NREL/ssc/commit/0b50eaf8968dbccae5c7227cbd1607268bcf6dee) . We need to reapply these changes in Develop.
> 
> There are also small differences between Patch and Develop in ssc/common.cpp. I don't know if the merge got this right. @sjanzou can you please check if this file is correct in this pull request?

@tyneises ,  Good catch! common.cpp has been updated in patch and the comparison with develop shows that the changes are not there (patch on left and develop on right) and common.cpp is not in this pull request!
image

It seems like some changes are not captured in this pull request - here is a list of differences from patch (left) and develop (right) as of 8/14/2024
image

All the files in this pull request look good to me; however, I think we need to do another pull request after patch 2 is released. Several of the merges for patch 2 are not included in this pull request as shown above.

**Review by sjanzou — APPROVED** [review]
The file changes in this pull request look fine; however, there are several changes in patch that are not in develop that are not included in this pull request - see my comment in the discussion.

**Comment by tyneises** [comment]
Thanks @sjanzou ! Should we keep this pull request open and try to complete the merge here (after patch 2 is released)?

**Review by dguittet — APPROVED** [review]
LGTM, thanks for handling this!

**Pull request merged**
