### PR TITLE
Address SAM issue #1733 while keeping functionality of SAM issue #1184

### PR DESCRIPTION
**Pull request by sjanzou**
To test:
1. pull SAM_1733 branch of ssc and patch branches of other repos and build
2. create PVWatts/Commercial case
3. Financial parameters page - set straight line depreciation years to 0
4. select straight line depreciation and run - error as expected
5. select different depreciation method and run - no error as expected.

See https://github.com/NREL/SAM/issues/1733 for simulation error in current release.

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
I'm still seeing the error after cleaning and rebuilding. This is for the default PVWatts / Commercial case switching to 5-yr MACRS after setting straight line depreciation years to zero:

image

**Review by mjprilliman — APPROVED** [review]
Worked for me when testing. Where else should SKIP_CONSTRAINT_CHECK be applied (question for a different issue/PR)?

I can't replicate the Windows test failure on my build.

**Review by sjanzou — COMMENTED** [review]
reviewed and tests with @mjprilliman

**Comment by sjanzou** [comment]
> Worked for me when testing. Where else should SKIP_CONSTRAINT_CHECK be applied (question for a different issue/PR)?
> 
> I can't replicate the Windows test failure on my build.

SKIP_CONSTRAINT_CHECK should be used anywhere for an optional ssc variable that is required only if some other variable is set to a specific value. The example of SAM issue https://github.com/NREL/SAM/issues/1733 is a perfect example in which the optional "years" value for straight line depreciation is required only if the depreciation selection is 2. Then the "years" input for the user should be checked to be positive (the CONSTRAINT field in the vartable).

**Pull request merged**
