### PR TITLE
fix(): Address bugs and increase usability of ml module model

### LINKED ISSUE #229: mlm module model support for irradmode=3 (poa from reference cell)
The mlm module model currently only considers poa components (i.e. `input.Ibeam`, `input.Idiff`, and `input.Ignd`) but will not use directly supplied user POA reference cell data.

It would be nice if the same logic found in `iec61853_module_t` were included at the beginning of `mlm_module_t`, something like:
```
if( input.radmode != 3 ){ // Skip module cover effects if using POA reference cell data 
		double S = (f_IAM_beam * input.Ibeam + f_IAM_diff * input.Idiff + groundRelfectionFraction * f_IAM_gnd * input.Ignd) * f_AM;
        }
else if(input.usePOAFromWF){ // Check if decomposed POA is required, if not use weather file POA directly
		double S = input.poaIrr;
	} 
else { // Otherwise use decomposed POA
		double S = (f_IAM_beam * input.Ibeam + f_IAM_diff * input.Idiff + groundRelfectionFraction * f_IAM_gnd * input.Ignd) * f_AM;
	}
```

### PR DESCRIPTION
**Pull request by caseyzak24**
Fixes #229, #227 and provides a short-term fix for #228. For now, changed ml model so that it calculates efficiency like the other models, i.e. 

eff = P / (module_area * POA_shaded_soiled)

However, the larger question of how module efficiency _should_ be calculated consistently remains open.

### CODE REVIEW

**Comment by nickdiorio** [comment]
Thanks @caseyzak24 for submitting this, that's great.  We'll take a look and let you know if we see anything that looks off.

**Comment by caseyzak24** [comment]
@nickdiorio I rebased this branch off of a more recent version of `develop` and then made a small change to the .gitignore. I'm not sure why this is causing the build to fail, but it the logs indicate it's related to the sdktool, which I didn't edit. I will try and dig around on my end and figure out why it's failing but if you could take a look as well that would be great.

**Comment by caseyzak24** [comment]
@nickdiorio I figured out what the issue was, my last commit deleted the sdktool folder for some unknown reason. The simplest solution was to roll back one commit and force push (the more recent commit was just to fix the repo index anyways). I'm not sure how to rerun the build but if you do it should pass.

**Comment by nickdiorio** [comment]
@caseyzak24 , no problem, my guess is that it's being rebuilt now, as it takes about 45 minutes on the Travis CI.  I think it will probably pass.  In any case, we'll try to get this integrated in the next week.

**Comment by nickdiorio** [comment]
Built and test locally, no issues.

**Pull request merged**
