### PR TITLE
Use calculated DNI for Allen method when there is no DNI in weather file

### LINKED ISSUE #1123: Allen model not working when weather file has no DNI
**Describe the bug**
Allen method is using the weather file DNI in calculation, is giving erroneous results without warning when there is no DNI in the weather file. 

**Expected behavior**
Either use decomposed DNI in calculation when no weather file DNI is provided or error out of the simulation with an appropriate error message. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mjprilliman**
-Fixes #1123 
-Fixes https://github.com/NREL/SAM/issues/1685
-Check for nan for weather file DNI, use calculated DNI as alternative

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
The simulation runs without crashing now, but the subhourly clipping loss seems very high. This is for the default Detailed PV / No Financial model with the weather file attached below:

image

Weather file used for testing:

[38.13_-86.34_psm3-tmy_60_tmy_no_dni.zip](https://github.com/NREL/ssc/files/14070083/38.13_-86.34_psm3-tmy_60_tmy_no_dni.zip)

**Comment by mjprilliman** [comment]
> The simulation runs without crashing now, but the subhourly clipping loss seems very high. This is for the default Detailed PV / No Financial model with the weather file attached below:
> 
> image
> 
> Weather file used for testing:
> 
> [38.13_-86.34_psm3-tmy_60_tmy_no_dni.zip](https://github.com/NREL/ssc/files/14070083/38.13_-86.34_psm3-tmy_60_tmy_no_dni.zip)

Which Irradiance data option did you use for these results? I'm having trouble replicating results.

**Comment by mjprilliman** [comment]
> I'm not seeing those results now. Perhaps I was in the wrong version of SAM. Please ignore my previous comment.
> 
> However, I am getting an exception in cmod_pvsamv1.cpp when I run a simulation with the default DNI+DHI option with the weather file that has no DNI data. The release version of SAM 2023.12.17 correctly generates an SSC error message, so I think this may have been introduced in this branch:
> 
> image

Paul, I caught that error too, apologies for not updating. I am working on a fix and will push shortly.

**Comment by cpaulgilman** [comment]
That will fix https://github.com/NREL/SAM/issues/1685

**Review by cpaulgilman — APPROVED** [review]
Looks good now. I tested weather file with no DNI with and without subhourly clipping. I'll work on the UI change for https://github.com/NREL/SAM/issues/1666 next.

**Pull request merged**
