### PR TITLE
Updated loss factor calculations for lifetime, subhourly options;

### PR DESCRIPTION
**Pull request by mjprilliman**
-See matching PR in SAM https://github.com/NREL/SAM/pull/1164
-Update calculations in loss factor setup for 7 different lifetime array options (single value, annual, monthly, weekly, daily, hourly, subhourly)
-Test in pvsamv1 for now

TODO:
-Apply to other relevant cmods

Test file included in https://github.com/NREL/SAM/pull/1164

### CODE REVIEW

**Comment by sjanzou** [comment]
@mjprilliman. since 1164 has conflicts that need to be resolved, I am not sure how to test this for single year models. Can you please provide a few ssc tests for the  7 different lifetime array options for maybe pvsamv1 and solar water heating or empirical trough so we can see results for both lifetime and single year models?

**Comment by mjprilliman** [comment]
> @mjprilliman. since 1164 has conflicts that need to be resolved, I am not sure how to test this for single year models. Can you please provide a few ssc tests for the 7 different lifetime array options for maybe pvsamv1 and solar water heating or empirical trough so we can see results for both lifetime and single year models?

Added tests for lifetime and non-lifetime application of losses

**Review by sjanzou — CHANGES_REQUESTED** [review]
Please review Geothermal Single Owner case with SAM pull request 1164.
Electricity Net Generation does not reflect the annual losses posted in the widget.
image

with results
image

Test file
[geothermal_annual_loss.zip](https://github.com/NREL/ssc/files/9808803/geothermal_annual_loss.zip)

**Comment by mjprilliman** [comment]
> Please review Geothermal Single Owner case with SAM pull request 1164. Electricity Net Generation does not reflect the annual losses posted in the widget. image
> 
> with results image
> 
> Test file [geothermal_annual_loss.zip](https://github.com/NREL/ssc/files/9808803/geothermal_annual_loss.zip)

This should be fixed in most recent commits

**Comment by sjanzou** [comment]
> > Please review Geothermal Single Owner case with SAM pull request 1164. Electricity Net Generation does not reflect the annual losses posted in the widget. image
> > with results image
> > Test file [geothermal_annual_loss.zip](https://github.com/NREL/ssc/files/9808803/geothermal_annual_loss.zip)
> 
> This should be fixed in most recent commits

Working well in last commit
image

**Review by sjanzou — APPROVED** [review]
Tested geothermal and empirical trough all modes with test file.
[emp_trough_subhourly.zip](https://github.com/NREL/ssc/files/9827103/emp_trough_subhourly.zip)

Seems good for lock down! Great work!

**Pull request merged**
